---
title: "behavioural-interventions-ma-nma-data-processing"
author: "diana danilenko"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries}
library(dplyr)
library(ggplot2)
library(texreg)
library(tidyverse) 
library(summarytools)
library(rmarkdown) 
library(devtools)
library(clubSandwich)
library(cowplot)
library(ggrepel) 
library(igraph)
library(nmarank)
library(knitr)
library(kableExtra)
library(gemtc)
library(rjags)
library(gridExtra)
library(readr)
library(boot)
library(haven)
library(stringr)
library(shiny)
library(readxl)
```

```{r set working directory and load functions}
# setwd("your working directory")
source("functions_v1.R")
source("functions_nma.R")
```

# only perform this if you have converted coefficients to smds and have mising data
```{r (opt.) complete data where possible and assign for manual completion otherwise}
dfinc <- read_excel("C:/Users/dand/Desktop/5-data-analysis/Living_Review_Full_Text_Coding_Aditya (1).xlsx")

dfinc <- dfinc %>%
  filter(! is.na(Authors))
dfinc <- dfinc %>%
  filter(! is.na(coder))

table(dfinc$ExclusionReasonLSR) 

# filter out excluded studies
dfinc <- dfinc %>% 
  filter((is.na(ExclusionReasonLSR))|ExclusionReasonLSR =="NA"|ExclusionReasonLSR =="Na"|ExclusionReasonLSR =="na")

num_cols <- c("test_statistic","coefficient", "coefficient_sd","total_sample_size","control_sample_size","treatment_sample_size","p_value")
dfinc[num_cols] <- lapply(dfinc[num_cols], as.numeric)

# record unique studies
unique_studies <- dfinc_all %>%
  distinct(documentID, Authors, `document title`, country)

table(unique_studies$country)

summary(dfinc$test_statistic)

# load the necessary package
if (!requireNamespace("stats", quietly = TRUE)) {
  install.packages("stats")
}

dfinc$df <- dfinc$total_sample_size - 1 # calculate degrees of freedom
dfinc$alpha <- dfinc$p_value / 2  # alpha for each tail (two-tailed test)

# calculate critical t-value where is.na(dfinc$test_statistic)
dfinc$test_statistic <- ifelse(is.na(dfinc$test_statistic), qt(1 - dfinc$alpha, dfinc$df),dfinc$test_statistic) 

summary(dfinc$test_statistic) 

dfinc$df <- NULL
dfinc$alpha <- NULL
```

```{r load and pre-process data}
# SPECIFY INPUT FILE HERE
dfinc <- readxl::read_xlsx("filepath")

# process effect size variables 
dfinc$effect_direction <- ifelse(dfinc$effect_direction == "decrease", -1, 
                                  ifelse(dfinc$effect_direction == "increase", 1, NA))

dfinc$PercentageChange <- abs(as.numeric(dfinc$PercentageChange))
dfinc$test_statistic <- abs(as.numeric(dfinc$test_statistic))
dfinc$coefficient_sd <- abs(as.numeric(dfinc$coefficient_sd))
dfinc$coefficient <- abs(as.numeric(dfinc$coefficient))
dfinc$diff_mean <- abs(as.numeric(dfinc$diff_mean))

dfinc$study_design <- ifelse(dfinc$study_design == "Pre-test/ post-test", "Pre-test/post-test", dfinc$study_design)
dfinc$significance_test <- ifelse(dfinc$significance_test == "f-test", "F-test", dfinc$significance_test)

dfinc <- dfinc %>% 
  filter(is.na(ExclusionReasonLSR) | ExclusionReasonLSR=='NA') %>%
  mutate(across(c(PercentageChange,coefficient, coefficient_sd, control_mean, control_sample_size, control_sd, treated_mean, treatment_sample_size, treated_sd, total_sample_size, diff_mean, pooled_sd, p_value, test_statistic), as.numeric))

dfinc <- dfinc %>%
  mutate(Opt_in_out = case_when(
    Opt_in_out == "Mandatory" ~ "No",
    Opt_in_out %in% c("Opt in", "Opt out") ~ "Yes",
    Opt_in_out == "Unclear" ~ NA_character_,
    TRUE ~ Opt_in_out  # optional: retain other values if any
  ))

```

```{r check risk of bias data for completeness}
rob_variables <- c(
  "DataCausal", "ConfounderPossibility", "ConfounderAll", "ConfounderJustifiedOmission",
  "ConfounderAccuracy", "ConfounderAnalysis", "SampleExchangeability", "SampleExclusion",
  "SampleGroupComparability", "SampleGroupDifferenceIntervention", "SampleBiasAdjustment",
  "AwareofStudy", "DataSelective", "DataSubgroups", "DataCausal", "StatsRecording",
  "StatsDescriptiveError", "StatsInferentialError", "StatsInferentialViolation"
)

# apply the transformation to each variable
for (var in rob_variables) {
  # mutate the variable based on "no" and "yes" text presence
  dfinc[[var]] <- ifelse(grepl("\\bno\\b", dfinc[[var]], ignore.case = TRUE), "No",
                       ifelse(grepl("\\byes\\b", dfinc[[var]], ignore.case = TRUE), "Yes", NA))
}

# check the tables of mutated variables
for (var in rob_variables) {
  print(table(dfinc[[var]]))
}
```

```{r process risk of bias variables}
# criterion 1: risk of confounding biases
dfinc <- dfinc %>%
  mutate(across(c(ConfounderPossibility, ConfounderAll, ConfounderJustifiedOmission, ConfounderAccuracy, ConfounderAnalysis), as.factor))

dfinc['cat_criterion1'] <- NA
dfinc$cat_criterion1 <- ifelse((dfinc$ConfounderPossibility == "No" | dfinc$ConfounderPossibility == "Seemingly no"), "low", 
                                ifelse((dfinc$ConfounderAll == "No" | dfinc$ConfounderAll == "Seemingly no"),ifelse((dfinc$ConfounderJustifiedOmission == "No" | dfinc$ConfounderJustifiedOmission == "Seemingly no"),"high",ifelse((dfinc$ConfounderAnalysis == "No" | dfinc$ConfounderAnalysis == "Seemingly no"),"high","low")),
                                       ifelse((dfinc$ConfounderAnalysis == "No" | dfinc$ConfounderAnalysis == "Seemingly no"),"medium","low")))

table(dfinc$cat_criterion1)

# criterion 2: risk of post-intervention/exposure selection biases
dfinc <- dfinc %>%
  mutate(across(c(SampleExchangeability, SampleExclusion, SampleGroupComparability, SampleGroupDifferenceIntervention, SampleBiasAdjustment), as.factor))

dfinc['cat_criterion2'] <- NA

dfinc$cat_criterion2 <- ifelse((dfinc$SampleExchangeability == "No" | dfinc$SampleExchangeability == "Seemingly no"),
                                ifelse((dfinc$SampleGroupComparability == "No" | dfinc$SampleGroupComparability == "Seemingly no"),
                                       ifelse((dfinc$SampleGroupDifferenceIntervention == "No" | dfinc$SampleGroupDifferenceIntervention == "Seemingly no"),"medium",
                                              ifelse((dfinc$SampleBiasAdjustment == "No" | dfinc$SampleBiasAdjustment == "Seemingly no"),"high","medium")),"medium"),
                                ifelse((dfinc$SampleExclusion == "No" | dfinc$SampleExclusion == "Seemingly no"  | dfinc$SampleExclusion == "Not applicable" | is.na(dfinc$SampleExclusion)),"low",ifelse((dfinc$SampleGroupComparability == "No" | dfinc$SampleGroupComparability == "Seemingly no"),
                                                                                                                                ifelse((dfinc$SampleGroupDifferenceIntervention == "No" | dfinc$SampleGroupDifferenceIntervention == "Seemingly no"),"medium",
                                                                                                                                       ifelse((dfinc$SampleBiasAdjustment == "No" | dfinc$SampleBiasAdjustment == "Seemingly no"),"high","medium")),"medium")))

table(dfinc$cat_criterion2)

# criterion 5: risk of detection biases
dfinc <- dfinc %>%
  mutate(across(c(AwareofStudy), as.factor))

dfinc['cat_criterion5'] <- NA

dfinc$cat_criterion5 <- ifelse((dfinc$AwareofStudy == "No" | dfinc$AwareofStudy == "Seemingly no" | dfinc$AwareofStudy == "Not applicable" | is.na(dfinc$AwareofStudy)),"low","high")

# check that these NAs are actually "low"

table(dfinc$cat_criterion5)

# criterion 6: risk of outcome reporting biases
dfinc <- dfinc %>%
  mutate(across(c(DataSelective, DataSubgroups, DataCausal), as.factor))

dfinc['cat_criterion6'] <- NA

dfinc$cat_criterion6 <- ifelse((dfinc$DataSelective == "No" | dfinc$DataSelective == "Seemingly no"), 
                                ifelse((dfinc$DataSubgroups == "No" | dfinc$DataSubgroups == "Seemingly no"), 
                                ifelse((dfinc$DataCausal == "No" | dfinc$DataCausal == "Seemingly no"),"low","medium"),
                                ifelse((dfinc$DataCausal == "No" | dfinc$DataCausal == "Seemingly no"),"medium","high")),
                                ifelse((dfinc$DataSubgroups == "No" | dfinc$DataSubgroups == "Seemingly no"),
                                       ifelse((dfinc$DataCausal == "No" | dfinc$DataCausal == "Seemingly no"),"medium","high"),"high"))

table(dfinc$cat_criterion6)

# criterion 7: risk of outcome assessment biases
dfinc <- dfinc %>%
  mutate(across(c(StatsRecording, StatsDescriptiveError, StatsInferentialError, StatsInferentialViolation), as.factor))

dfinc['cat_criterion7'] <- NA

dfinc$cat_criterion7 <- ifelse((dfinc$StatsRecording == "No" | dfinc$StatsRecording == "Seemingly no"),
                                ifelse((dfinc$StatsDescriptiveError == "No" | dfinc$StatsDescriptiveError == "Seemingly no"),
                                       ifelse((dfinc$StatsInferentialError == "No" | dfinc$StatsInferentialError == "Seemingly no"),"low","high"),
                                       "high"),
                                ifelse((dfinc$StatsDescriptiveError == "No" | dfinc$StatsDescriptiveError == "Seemingly no"),"medium","high"))

table(dfinc$cat_criterion7)
```

```{r print risk of bias % studies per criterion}
round(prop.table(table(dfinc_all$cat_criterion1)) * 100, 1)
round(prop.table(table(dfinc_all$cat_criterion2)) * 100, 1)
round(prop.table(table(dfinc_all$cat_criterion5)) * 100, 1)
round(prop.table(table(dfinc_all$cat_criterion6)) * 100, 1)
round(prop.table(table(dfinc_all$cat_criterion7)) * 100, 1)
```

```{r summarise risk of bias values in 1 variable}
dfinc <- dfinc %>%
  mutate(across(c(cat_criterion1, cat_criterion2, cat_criterion5, cat_criterion6, cat_criterion7),
                ~ case_when(
                  . == "low" ~ 1,
                  . == "medium" ~ 2,
                  . == "high" ~ 3,
                  TRUE ~ NA_real_
                )))

dfinc <- mutate(dfinc, 
                cat_criteria_sum = cat_criterion1+cat_criterion2+cat_criterion5+cat_criterion6+cat_criterion7)
dfinc <- mutate(dfinc,
                cat_criteria_sum = case_when(cat_criteria_sum <= 5 ~"low",
                                           ((cat_criteria_sum > 5) & (cat_criteria_sum <= 10)) ~ "medium",
                                           cat_criteria_sum >10 ~ "high"))

table(dfinc$cat_criteria_sum)
```

```{r (opt.) exclude outliers or any other categories of observations}
# when running the analysis for the first time, skip this and come back after chunk #17 on 'identify outliers using cook's d'
# exclude outliers as identified based on cook's d and by looking at them (we exclude CPP and PLP later, which excludes 1 outlier)

# exclude Meub et al. 2019 "23-182"
dfinc <- dfinc %>% filter(! documentID == "23-182")
# exclude Staats et al. 2004 "23-305"
dfinc <- dfinc %>% filter(! documentID == "23-305")

dfinc$`Critical Peak Pricing` <- as.numeric(dfinc$`Critical Peak Pricing`)
dfinc$`Peak Load Pricing` <- as.numeric(dfinc$`Peak Load Pricing`)

dfinc <- dfinc %>% filter(dfinc$`Critical Peak Pricing` == 0 | is.na(dfinc$'Critical Peak Pricing')) 
dfinc <- dfinc %>% filter(dfinc$`Peak Load Pricing` == 0 | is.na(dfinc$'Peak Load Pricing'))
```

```{r calculate smd and smd var}
# CALCULATING STANDARDIZED SIZES AND VARIANCES

# formulas taken from Ringquist
# compute effect measures (r_coefficient, smd, fisher's z)
dfinc <- mutate(dfinc,
                # calculating r coefficient for regression results using sample_size  
                # readjust the calculation as required based on the type of significance test
                # currently we assume NAs, not specified and all other types as t-test 
                r_coefficient = ifelse((significance_test == "t-test"), ((`test_statistic`)^2/((`test_statistic`)^2 + `total_sample_size`))^(1/2) * effect_direction * -1 , # result is adjusted for the effect direction and inverted.
                                       ifelse((significance_test == "z-test" | significance_test == "X^2 Test"), (`test_statistic`^2/`total_sample_size`)^(1/2)* effect_direction * -1 , NA)), 


                # calculating smd for experiments with difference of means results
                pooled_sd = ifelse(is.na(pooled_sd) & study_design == "Pre-test/post-test", (((`treatment_sample_size`-1)*control_sd^2 + (`treatment_sample_size`-1)*treated_sd^2)/(`treatment_sample_size` + `treatment_sample_size` - 2))^(1/2),
                                   ifelse(is.na(pooled_sd) & study_design != "Pre-test/post-test", (((`control_sample_size`-1)*control_sd^2 + (`treatment_sample_size`-1)*treated_sd^2)/(`control_sample_size` + `treatment_sample_size` - 2))^(1/2),
                                          pooled_sd)),
            
                # calculate standardized mean differences
                smd1= ifelse(`statistical_technique` == "Difference of means" | `statistical_technique` == "ANOVA" , `diff_mean`/`pooled_sd`, NA),
    
                smd2= ifelse(((`statistical_technique` == "Difference of means" | `statistical_technique` == "ANOVA") & (significance_test == "F-test" | significance_test == "H-test") & study_design == "Control-treatment"),
                             (`test_statistic`/`control_sample_size`/`treatment_sample_size`*(`treatment_sample_size` + `control_sample_size`))^(1/2),
                             ifelse(((`statistical_technique` == "Difference of means" | `statistical_technique` == "ANOVA") & (significance_test == "F-test" | significance_test == "H-test") & study_design == "Difference in Difference"),
                                    (`test_statistic`/`control_sample_size`/`treatment_sample_size`*(`treatment_sample_size` + `control_sample_size`))^(1/2),
                                    ifelse(((`statistical_technique` == "Difference of means" | `statistical_technique` == "ANOVA") & (significance_test == "F-test" | significance_test == "H-test") & study_design == "Pre-test/post-test"),
                                           (`test_statistic`/(`treatment_sample_size`)^2*(2*`treatment_sample_size`))^(1/2),   #using treatment sample = control sample
                                           
                                           ifelse(((`statistical_technique` == "Difference of means" | `statistical_technique` == "ANOVA") & (significance_test == "t-test" | significance_test == "z-test") & study_design == "Control-treatment"),
                                                  `test_statistic` * (1/`control_sample_size`/`treatment_sample_size`*(`treatment_sample_size` + `control_sample_size`))^(1/2),
                                                  ifelse(((`statistical_technique` == "Difference of means" | `statistical_technique` == "ANOVA") & (significance_test == "t-test" | significance_test == "z-test") & study_design == "Difference in Difference"),
                                                         `test_statistic` * (1/`control_sample_size`/`treatment_sample_size`*(`treatment_sample_size` + `control_sample_size`))^(1/2),
                                                         ifelse(((`statistical_technique` == "Difference of means" | `statistical_technique` == "ANOVA") & (significance_test == "t-test" | significance_test == "z-test") & study_design == "Pre-test/post-test"),
                                                                `test_statistic` * (1/(`treatment_sample_size`)^2*(2*`treatment_sample_size`))^(1/2), #using treatment sample = control sample
                                                                
                                                                NA)))))),
                
                smd = smd1,
                smd = ifelse(is.na(smd1), smd2, smd1),
                
                # converting d into r for difference of means regressions and ANOVA
                r_coefficient = ifelse(`statistical_technique`  %in% c("Difference of means", "ANOVA"), smd/(smd^2+4)^(1/2), r_coefficient),
                
                # converting r into smd
                smd = ifelse(
                  is.na(smd1),
                  2*r_coefficient/(1-r_coefficient^2)^0.5,
                    smd1
                  ),
                
                zi = 0.5 * log((1+r_coefficient) / (1-r_coefficient))
)


# Compute variance of effect measures
dfinc <- mutate(dfinc,
                # variance of r
                var_r1 = (1-r_coefficient^2)^2/(`total_sample_size` - 1), 
                var_r2 = coefficient_sd^2, 
                var_r = var_r1,
                var_r = ifelse(is.na(var_r1), var_r2, var_r1),
 
                # variance of smd
                var_smd = ifelse(control_sample_size>0, ((`control_sample_size`+`treatment_sample_size`)/(`control_sample_size`*`treatment_sample_size`)) + (smd^2/(2*(`control_sample_size`+`treatment_sample_size`))),
                                 ((`treatment_sample_size`+`treatment_sample_size`)/(`treatment_sample_size`*`treatment_sample_size`)) + (smd^2/(2*(`treatment_sample_size`+`treatment_sample_size`)))),
           
                # coverting var_smd to var_r
                var_r = ifelse(is.na(var_r),
                               (4^2*var_smd)/((smd^2+4)^3),
                               var_r),
            
                #converting var_r to var_smd
                var_smd = ifelse(is.na(var_smd),
                                 4*var_r/(1-r_coefficient^2)^3,
                                 var_smd),
           
                # #variance of Zs
                vi   = 1/(`total_sample_size` - 3)
)

# filter only observations with complete smd & var[smd]
dfinc <- dfinc %>%
  filter(!is.na(smd) & !is.na(var_smd))
print(paste0(nrow(dfinc), " data can be used after all"))

summary(dfinc$smd)
```

```{r clean data and introduce controls}
# DATA CLEANING AND CONTROLS
dfinc$study_design <- as.factor(dfinc$study_design)

table(dfinc$'randomisation_dummy')

dfinc <- dfinc %>%
  mutate(
    randomisation_level = case_when(
      `Randomisation method` %in% c("no", "No", "none", "not done", "Not randoized", "not randomized", "Not randomized") ~ "not randomised",
      `Randomisation method` %in% c("Household", "household level", "Household level", "Household level randomization", 
                                    "Household stratified randomization", "Individual Household", "individual Household - RCT", 
                                    "Individual Household - RCT", "Individual Household -RCT", "Stratified random sampling at household level", 
                                    "Room level randomization") ~ "household",
      `Randomisation method` %in% c("Floor level randomisation", "geographically-contiguous “block batch”", 
                                    "Grouped Household", "Grouped Household - Contiguous block group", 
                                    "Grouped Household - randomized block design", "Grouped Household - RCT") ~ "group"
    )
  ) %>%
  mutate(
    randomisation_level = case_when(
      is.na(randomisation_level) & randomisation_dummy %in% c("no", "No") ~ "not randomised",
      is.na(randomisation_level) & randomisation_dummy %in% c("yes", "Yes") ~ "randomised",
      TRUE ~ randomisation_level
    )
  )

dfinc <- mutate(dfinc, 
                ElectricityUse = `controls Electricity use`,
                ElectricityPrice = `controls Energy prices`,
                EnvironmentAttitudes =  `controls Environmental attitudes`,
                HouseholdType =  `controls HH controls (demographics)`,
                ResidenceType = `controls Residence controls`,
                Season =   `controls Seasonal controls`,
                Weather = `controls Weather controls`,
                
                Region = case_when(
                  country %in% c("India") ~ 'Asia',
                  country %in% c("Japan") ~ 'Asia',
                  country %in% c("South Korea") ~ 'Asia',
                  country %in% c("Singapore") ~ 'Asia',
                  country %in% c("China") ~ 'Asia',
                  country %in% c("Bangladesh") ~ 'Asia',
                  country %in% c("Taiwan") ~ 'Asia',
                  country %in% c("Thailand") ~ 'Asia',
                  country %in% c("Vietnam") ~ 'Asia',
                  country %in% c("Indonesia") ~ 'Asia',
                  
                  country %in% c("Austria") ~ 'Europe excl. UK',
                  country %in% c("Denmark") ~ 'Europe excl. UK',
                  country %in% c("Finland") ~ 'Europe excl. UK',
                  country %in% c("France") ~ 'Europe excl. UK',
                  country %in% c("Germany") ~ 'Europe excl. UK',
                  country %in% c("Italy") ~ 'Europe excl. UK',
                  country %in% c("Latvia") ~ 'Europe excl. UK',
                  country %in% c("Netherlands") ~ 'Europe excl. UK',
                  country %in% c("Northern") ~ 'Europe excl. UK',
                  country %in% c("Poland") ~ 'Europe excl. UK',
                  country %in% c("Sweden") ~ 'Europe excl. UK',
                  country %in% c("Switzerland") ~ 'Europe excl. UK',
                  country %in% c("Ireland") ~ 'Europe excl. UK',
                  country %in% c("Portugal") ~ 'Europe excl. UK',
                  country %in% c("Spain") ~ 'Europe excl. UK',
                  country %in% c("Lithuania") ~ 'Europe excl. UK',
                  country %in% c("Moldova") ~ 'Europe excl. UK',
                  country %in% c("Monaco") ~ 'Europe excl. UK',
                  country %in% c("Serbia") ~ 'Europe excl. UK',
                  country %in% c("Republic of Georgia") ~ 'Europe excl. UK',
                  country %in% c("Romania") ~ 'Europe excl. UK',
                  
                  country %in% c("Australia") ~ 'Others',
                  country %in% c("Colombia") ~ 'South America',
                  country %in% c("Ecuador") ~ 'South America',
                  country %in% c("Israel") ~ 'Others',
                  country %in% c("South Africa") ~ 'Others',
                  country %in% c("Canada") ~ 'North America',
                  country %in% c("Mexico") ~ 'Central America',
                  country %in% c("Iran") ~ 'Others',
                  country %in% c("Chile") ~ 'South America',
                  country %in% c("Brasil", "Brazil") ~ 'South America',
                  country %in% c("Ghana") ~ 'Others',
                  
                  country %in% c("United Kingdom", "England") ~ 'United Kingdom',
                  country %in% c("United States") ~ 'North America',
                  
                  TRUE ~ country),
                
                StatsMethod = case_when( statistical_technique %in% c("Difference of means", "ANOVA") ~ "MeansDifferences",
                                         # statistical_technique %in% c("Household Fixed effects regression ", "Time & Household Fixed effects regression ", "Fixed effects regression ",
                                         #                              "Random effects regression ") ~ "PanelEffects",
                                         statistical_technique %in% c("OLS regression") ~ "OLS",
                                         TRUE ~ "PanelEffects"),
                
                StudyDesign = case_when( study_design  %in% c("Control-treatment") ~ "Control-treatment",
                                         study_design  %in% c("Difference in Difference") ~ "DID",
                                         study_design  %in% c("Pre-test/ post-test", "Pre-test/post-test", "Pre-test / post-test") ~ "PrePost"),
                
                # creates a binary Control variable indicating whether a control group is present based on the control_sample_size.
                Control = if_else(control_sample_size>0, 1, 
                                  if_else(is.na(control_sample_size), 0, 0),0),
                
                BaselineConsumption = `baselineConsumption`, 
                InterventionDuration = interventionDuration,
                
                Randomisation = case_when(`Randomisation method`  %in% c("no", "No", "none", "None", "not done","Not randoized", "not randomized", "Not randomized", 
                                                                         "Not randomized, lower socio economic status population") ~ "No",
                                          # `Randomisation method`  %in% c(NA, "No details") ~ "NA",
                                          TRUE ~ "Yes"),  
                # Were households first selected and then allowed to opt out of the intervention or were the households required to opt-in to the intervention or neither
    
                
                After2000 = case_when(`document PY` > 2000 ~ "After",
                                      TRUE ~ "Before"),
                
                StudyYear = `document PY`,
                
                Followup = case_when(interventionFollowup>0 ~ 1,
                                     interventionFollowup == NA ~ 0, 
                                     TRUE ~ 0),
                
                Geographic_Scope = ifelse(geographic_scope %in% c("Country", "State", "City", "Municipality", "Smaller than municipality"), "Macro", "Minor")
                
)

# assume no controls if coded NA
dfinc$Weather <- ifelse(is.na(dfinc$Weather),"0",dfinc$Weather) 
dfinc$StudyDesign <- ifelse(grepl("23-168", dfinc$effectID), "PrePost", dfinc$StudyDesign)

# sets and reorders the factor levels for StudyDesign, StatsMethod, and Region.
dfinc$StudyDesign <- factor(dfinc$StudyDesign, levels = c("DID", "Control-treatment", "PrePost"))
dfinc$StudyDesign <- relevel(dfinc$StudyDesign, ref =  "PrePost")

dfinc$StatsMethod <- as.factor(dfinc$StatsMethod)
dfinc$StatsMethod <- factor(dfinc$StatsMethod, levels = c("MeansDifferences", "OLS", "PanelEffects"))
dfinc$StatsMethod <- relevel(dfinc$StatsMethod, ref = "OLS")

dfinc$Region <- as.character(dfinc$Region)
dfinc$Region <- ifelse(dfinc$Region == "United States", "North America", dfinc$Region)
dfinc$Region <- as.factor(dfinc$Region)
dfinc$Region <- factor(dfinc$Region, levels = c("Asia", "North America", "United Kingdom","Europe excl. UK", "Others"))
dfinc$Region <- relevel(dfinc$Region, ref = "North America")

dfinc$InterventionID <- 1:nrow(dfinc)

```

```{r create a table of included studies}
library(openxlsx)
dfinc$Authors <- gsub("<br>", "", dfinc$Authors)

unique_combinations <- unique(dfinc_all[, c("documentID", "Authors", "document PY")])

# unique_combinations <- unique(dfinc_all[, c("documentID", "Authors", "document PY", "country","total_sample_size")])

# print(mean(unique_combinations$total_sample_size))

# first_per_doc <- unique_combinations[!duplicated(unique_combinations$documentID), ]
# sum(first_per_doc$total_sample_size, na.rm = TRUE)

write.xlsx(unique_combinations, "combined_included_2025-06-18.xlsx")
```

```{r attach newer data to older data and deduplicate}
dfinc_new <- dfinc
load("lsr_data.R")
dfinc <- dfinc[!duplicated(dfinc[, c("Authors", "smd", "var_smd", "effectID")]), ]
n0 <- nrow(dfinc)

dfinc <- dfinc %>%
  filter(!grepl("Dertwinkel-Kalt", Authors)) %>%
  filter(!grepl("Xing Menglin", Authors)) %>%
  filter(!grepl("Sudarmaji", Authors)) 
# are these studies now in the sample?

dfinc <- unique(rbind(dfinc, dfinc_new))

#dfinc_dedup <- dfinc[!duplicated(dfinc$effectID), ]
# resolve the issue of multiple data points existing with the same effectID

dfinc <- dfinc[!duplicated(dfinc[, c("Authors", "smd", "var_smd", "effectID")]), ]

n1 <- nrow(dfinc)

cat("New data points added:", n1 - n0, "\n")
```

```{r save data in R database}
# save data in R database before outlier exlusion
save(dfinc,file = paste0("lsr_data_", today, ".R"))
```

```{r write summary statistics}
# factor variables
sumVarsFactor <- c(#"intervention",
                   "Opt_in_out",
                   "StatsMethod",
                   "StudyDesign",
                   "Randomisation",
                   "Region",
                   "Weather",
                   "cat_criterion1",
                   "cat_criterion2",
                   "cat_criterion5",
                   "cat_criterion6",
                   "cat_criterion7")

# one older study is missing RoB variables as we are unable to retrieve the full text anymore

dfinc$cohen_d <- dfinc$smd
dfinc$d_var <- dfinc$var_smd

# numeric variables
sumvarsNum <- c("cohen_d",
                "d_var")

dfinc[sumVarsFactor] <- lapply(dfinc[sumVarsFactor], factor)
dfinc[sumvarsNum] <- lapply(dfinc[sumvarsNum], as.numeric)

# for(col in names(select(dfinc,all_of(sumVarsFactor)))) {
#   freq_table <- freq(dfinc[[col]], style = "rmarkdown", cumul=FALSE, report.nas = FALSE, totals = FALSE)
#   print(freq_table)
# }

today <- Sys.Date()
docfile <- paste0("summarystatistics_all_", today, ".doc")
htmlfile <- paste0("summarystatistics_all_", today, ".html")

dfinc %>%
  select(all_of(c(sumVarsFactor,sumvarsNum))) %>% 
  dfSummary(graph.col = T, style = "grid", na.col = FALSE) %>%
  print(file = htmlfile)
 rmarkdown::render(htmlfile, output_file = docfile)
```

```{r process intervention variables}
# ANALYSIS USING 5 MAIN CATEGORIES MAPPING - FEEDBACK, INFORMATION, SOCIAL, MOTIVATION, MONETARY

# Prepare data for analysis
dfinc_all <- dfinc %>%
  mutate(
    Feedback = ifelse(`Historical` == 1  | `Home Energy Report` == 1 | `In home display` == 1 | `Smart Metering` == 1, 1, 0),
    Information = ifelse(`Awareness Campaign` == 1 | `Bills` == 1 |`Home audits` == 1 | `tips` == 1, 1, 0),
    SocialComparison = ifelse(`Injunctive Norm / Social Norm` == 1 | `peer comparison` == 1, 1, 0),
    Motivation = ifelse(`Commitment strategies` == 1 | `Competition` == 1 | `Gamification` == 1 | `Goal Setting` == 1 | `Moral suasion` == 1, 1, 0),
    # DynamicPricing = ifelse(`Critical Peak Pricing` == 1 | `Dynamic Pricing` == 1 | `Peak Load Pricing` == 1 | `Real-time Pricing` == 1 | `ToU` == 1,  1, 0),
    MonetaryRewards = ifelse(`Critical Peak Pricing` == 1 | `Dynamic Pricing` == 1 | 
                               `Peak Load Pricing` == 1 | `Real-time Pricing` == 1 | `ToU` == 1 |`Rewards` == 1, 1, 0)
  ) %>% 
  replace_na(list(
    Feedback = 0,
    Information = 0,
    SocialComparison = 0,
    Motivation = 0,
    MonetaryRewards = 0#,
    #DynamicPricing = 0
  )) %>%
  mutate(Feedback_2 = ifelse(Feedback == 1, "Feedback1", "Feedback0")) %>% 
  mutate(Information_2 = ifelse(Information == 1, "Information1", "Information0")) %>% 
  mutate(SocialComparison_2 = ifelse(SocialComparison == 1, "SocialComparison1", "SocialComparison0")) %>% 
  mutate(Motivation_2 = ifelse(Motivation == 1, "Motivation1", "Motivation0")) %>% 
  mutate(MonetaryRewards_2 = ifelse(MonetaryRewards == 1, "MonetaryRewards1", "MonetaryRewards0")) %>%
  #mutate(DynamicPricing_2 = ifelse(DynamicPricing == 1, "DynamicPricing1", "DynamicPricing0")) %>%
  mutate(Treatment1 = paste(Feedback_2, Information_2, SocialComparison_2, Motivation_2, MonetaryRewards_2, sep = ":")) %>%
  filter(Treatment1 != "Feedback0:Information0:SocialComparison0:Motivation0:MonetaryRewards0") %>% # Exclude effect size that doesn't get mapped to a valid intervention
  mutate(treatment = mapping_vector[Treatment1])

dfinc_all <- dfinc_all %>%
  mutate(intervention = apply(select(., Feedback, Information, SocialComparison, Motivation, MonetaryRewards), 1, function(row) {
    cols <- names(row)[which(row == 1)]   # get names of columns where the value is 1
    if(length(cols) > 0) {
      paste(cols, collapse = "_")         # concatenate with underscore
    } else {
      NA                                  # if no values are 1, set to NA
    }
  }))

dfinc_all$InterventionID <- 1:nrow(dfinc_all)

dfinc_all$Feedback <- factor(dfinc_all$Feedback)
dfinc_all$Information <- factor(dfinc_all$Information)
dfinc_all$SocialComparison <- factor(dfinc_all$SocialComparison)
dfinc_all$Motivation <- factor(dfinc_all$Motivation)
dfinc_all$MonetaryRewards <- factor(dfinc_all$MonetaryRewards)
# dfinc_all$DynamicPricing <- factor(dfinc_all$DynamicPricing)

# use this for showing n observations per intervention
int_count <- table(dfinc_all$intervention)
print(int_count <- table(dfinc_all$intervention))
```

```{r write summary statistics per intervention}
dfinc4 <- dfinc_all %>% filter(dfinc_all$intervention %in% c("Feedback", "Information", "SocialComparison", "Motivation", "MonetaryRewards")) 

# add audit as a separate category if desirable

# write summary statistics for all different intervention categories
# dfinc4 <- dfinc

dfinc4[sumVarsFactor] <- lapply(dfinc4[sumVarsFactor], factor)
dfinc4[sumvarsNum] <- lapply(dfinc4[sumvarsNum], as.numeric)

dfinc4$cohen_d <- dfinc4$smd # rename as we're using calculation for cohen's d rather than smd
dfinc4$d_var <- dfinc4$var_smd

# list of interventions
unique_interventions <- unique(dfinc4$intervention)

# Create an empty list to store the summary tables for each intervention
summary_list <- list()

# Loop through each intervention and create the summary
for (interv in unique_interventions) {
  # Filter the data for the specific intervention
  df_interv <- dfinc4 %>% filter(intervention == interv)
  
  # Create the summary statistics for the filtered data
  summary <- df_interv %>%
    select(all_of(c(sumVarsFactor, sumvarsNum))) %>% 
    dfSummary(graph.col = FALSE, style = "grid", na.col = FALSE)
  
  # Add the summary table to the list, with the name of the intervention as the title
  summary_list[[interv]] <- summary
}

# Combine all summaries into a single data frame, with an extra column for the intervention
combined_summary <- bind_rows(
  lapply(names(summary_list), function(interv) {
    summary_data <- summary_list[[interv]]
    summary_data <- as.data.frame(summary_data)
    summary_data$Intervention <- interv
    return(summary_data)
  })
)

today <- Sys.Date()
htmlfile <- paste0("summarystatistics_combined-",today,".html")
docfile <- paste0("summarystatistics_combined-",today,".doc")

# Save the combined summary as a single HTML file
combined_summary %>%
  kable("html", escape = FALSE, caption = "Summary Statistics by Intervention") %>%
  kable_styling(full_width = TRUE) %>%
  save_kable(htmlfile)

# Convert the HTML to a DOC file using rmarkdown
rmarkdown::render(
  input = htmlfile,
  output_file = docfile
)
```